export interface WpTarget {
  siteUrl: string;
  username: string;
  appPassword: string;
}

async function wpFetch(target: WpTarget, path: string, opts: RequestInit = {}) {
  const base = target.siteUrl.replace(/\/$/, "");
  const credentials = btoa(`${target.username}:${target.appPassword}`);
  const res = await fetch(`${base}/wp-json${path}`, {
    ...opts,
    headers: {
      Authorization: `Basic ${credentials}`,
      "Content-Type": "application/json",
      ...(opts.headers || {}),
    },
  });
  if (!res.ok) {
    const err = await res.json().catch(() => ({}));
    throw new Error(`WordPress API ${res.status}: ${(err as { message?: string }).message || res.statusText}`);
  }
  return res.json();
}

export async function validateWp(target: WpTarget): Promise<{ name: string }> {
  return wpFetch(target, "/wp/v2/users/me") as Promise<{ name: string }>;
}

// Writes a Must-Use Plugin that adds security headers
export async function createMuPlugin(target: WpTarget, phpCode: string): Promise<string> {
  // WordPress REST API doesn't have a native file endpoint — use custom endpoint if available
  // Fallback: inject via options (requires a custom endpoint plugin)
  // We return the code to be manually placed as a .php file in wp-content/mu-plugins/
  return phpCode;
}

export async function updateThemeOption(target: WpTarget, optionName: string, value: string): Promise<void> {
  await wpFetch(target, "/wp/v2/settings", {
    method: "POST",
    body: JSON.stringify({ [optionName]: value }),
  });
}

export async function getActiveTheme(target: WpTarget): Promise<string> {
  const data = await wpFetch(target, "/wp/v2/themes?status=active") as { stylesheet: string }[];
  return data[0]?.stylesheet || "unknown";
}

export function generateWpMuPlugin(securityHeaders: string[]): string {
  const lines = securityHeaders.map(h => {
    const [name, ...rest] = h.split(": ");
    return `  header('${name}: ${rest.join(": ")}');`;
  });
  return `<?php
/**
 * Plugin Name: SecFixer Security Headers
 * Description: Auto-generated by SecFixer SaaS — security headers hardening.
 * Version: 1.0
 */
defined('ABSPATH') || exit;

add_action('send_headers', function() {
${lines.join("\n")}
});
`;
}
